framework:
    secret: '%env(APP_SECRET)%'

    session:
        handler_id: ~
        cookie_secure: auto
        cookie_samesite: lax

    php_errors:
        log: true

    cache:
        prefix_seed: safebeat_application

        # Redis
        #app: cache.adapter.redis
        #default_redis_provider: redis://localhost
