parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    Safebeat\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    Safebeat\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # Doctrine Repositories
    Safebeat\Repository\RefreshTokenRepository:
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - Safebeat\Entity\RefreshToken
